modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/chimericdream/minekea-fabric/issues"
license = "Insert License Here"

[[mods]]
modId = "minekea"
version = "${version}"
displayName = "Minekea"
authors = "chimericdream"
description = '''
Simple, functional, decorative blocks for all your building and storage needs (some assembly required)
'''
#logoFile = ""

[[dependencies.minekea]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minekea]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.minekea]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.minekea]]
modId = "chimericlib"
type = "required"
versionRange = "[2.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.minekea]]
modId = "patchouli"
type = "optional"
versionRange = "[1.21-87,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "minekea.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
